apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartpagesplusuiapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: smartpagesplusuiapp
    spec:
      containers:
      - name: smartpagesplusuiapp
        image: webapp:1
        # for local development against minikube registry
        imagePullPolicy: Never        
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: smartpagesplusuiapp-service
  labels:
    app: smartpagesplusuiapp-service
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: smartpagesplusuiapp